micronaut:
    application:
        name: gorm-test

#Uncomment to set server port
#    server:
#        port: 8080

---
dataSource:
    dbCreate: update
    driverClassName: org.h2.Driver
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    url: jdbc:h2:./gormTest
    username: root
    password: ""
